# Generated by Django 5.1.6 on 2025-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='d',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=1),
        ),
    ]
