# Generated by Django 5.1.6 on 2025-02-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
