# Generated by Django 5.1.6 on 2025-02-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_choice_text_choice_a_choice_b_choice_c_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
