# Generated by Django 5.1.6 on 2025-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время входа'),
        ),
        migrations.AddField(
            model_name='student',
            name='test_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания теста'),
        ),
        migrations.AddField(
            model_name='student',
            name='test_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала теста'),
        ),
    ]
